{{- if .Values.proxmox.secret.create }}
---
kind: Secret
apiVersion: v1
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: {{ include "cluster-api-kamaji-proxmox.cluster-name" $ | quote }}
  name: {{ include "cluster-api-kamaji-proxmox.proxmox-secret-name" . }}
  namespace: {{ .Release.Namespace }}
stringData:
  url:    {{ .Values.proxmox.url | quote }}
  token:  {{ .Values.proxmox.tokenId | quote }}
  secret: {{ .Values.proxmox.tokenSecret | quote }}
{{- end }}
